{{- if .Values.storage.enabled -}}
{{- if .Values.backup.enabled -}}
{{- $fullName := include "bitwarden.fullname" . -}}
{{- if .Capabilities.APIVersions.Has "batch/v1"}}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ $fullName }}-database-backup
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  # Disallow concurrency if writing the same file
  {{ if .Values.backup.timestamp -}}
  concurrencyPolicy: Allow
  {{ else }}
  concurrencyPolicy: Forbid
  {{ end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $fullName }}-database-backup
            image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
            imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
            env:
            - name: SOURCE_DATABASE
              value: {{ .Values.storage.path}}/db.sqlite3
            - name: BACKUP_DATABASE
              value: {{ .Values.backup.path }}/backup.sqlite3
            - name: TIMESTAMP_BACKUP
              value: {{ .Values.backup.timestamp | quote}}
            - name: TIMESTAMP_FILE
              value: {{ .Values.backup.timestamp_file | quote}}
            volumeMounts:
            - mountPath: {{ .Values.storage.path }}
              name: data-storage
            - mountPath: {{ .Values.backup.path }}
              name: backup-storage
            {{- with .Values.backup.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          volumes:
          - name: data-storage
            persistentVolumeClaim:
              claimName: {{ $fullName }}-pv
          - name: backup-storage
            persistentVolumeClaim:
              claimName: {{ $fullName }}-backup-pv
          restartPolicy: OnFailure
          {{- with .Values.backup.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
